# Generated by Django 5.1.1 on 2024-11-13 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App1", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "tz",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=50)),
                ("age", models.IntegerField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orderDate", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("address", models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name="Student",
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "person",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="App1.person",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mocher",
            fields=[
                (
                    "person",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="App1.person",
                    ),
                ),
                ("salary", models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="App1.store"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="App1.client"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="stores",
            field=models.ManyToManyField(through="App1.Order", to="App1.store"),
        ),
        migrations.AddField(
            model_name="store",
            name="mocher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="App1.mocher"
            ),
        ),
    ]
